-- AlterTable
ALTER TABLE "TimeEntry" ADD COLUMN IF NOT EXISTS "paternityHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "permesso104Hours" DECIMAL(65,30) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasPaternityLeave" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "hasPermesso104" BOOLEAN NOT NULL DEFAULT false;
